version: '3.1'

networks:
  health-monitor:
    external: true

services:
  thanos-receive:
    image: quay.io/thanos/thanos:v0.31.0
    volumes:
      - ./thanos/:/etc/thanos/
      - /prometheus_data:/prometheus
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime        
    command:
      - 'receive'
      - '--tsdb.path=/prometheus'
      - '--grpc-address=0.0.0.0:10907'
      - '--http-address=0.0.0.0:10909'
      - '--receive.replication-factor=1'
      - "--label=receive_replica=\"0\""
      - "--label=receive_cluster=\"cloud\""
      - '--receive.local-endpoint=127.0.0.1:10907'
      - '--remote-write.address=0.0.0.0:10908'
      # - '--http.config=/etc/thanos/thanos_web.yaml'
      - '--objstore.config-file=/etc/thanos/bucket-config.yaml'
      - '--log.level=debug'
    ports:
      - 10908:10908
    # depends_on:
    #   - thanos-sidecar-cloud
    # restart: always
    networks:
      health-monitor:
        ipv4_address: "172.10.0.1"

  thanos-store-gateway:
    image: quay.io/thanos/thanos:v0.31.0
    volumes:
      - ./thanos/:/etc/thanos/
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    command:
      - 'store'
      - '--grpc-address=0.0.0.0:10091'
      - '--http-address=0.0.0.0:10902'
      - '--data-dir=/tmp/thanos/store'
      - '--objstore.config-file=/etc/thanos/bucket-config.yaml'
      - '--log.level=debug'
    # restart: always
    networks:
      health-monitor:
        ipv4_address: "172.10.0.2"
   
  thanos-querier:
    image: quay.io/thanos/thanos:v0.31.0
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    command:
      - 'query'
      - '--log.level=debug'
      - '--grpc-address=0.0.0.0:10091'
      - '--http-address=0.0.0.0:10902'
      # - '--query.replica-label=replica'
      # - '--store=thanos-sidecar-cloud:10091'
      - '--store=172.10.0.2:10091'
      - '--store=172.10.0.6:10091'
      - '--store=172.10.0.1:10907'
    ports:
      - 10902:10902
    # depends_on:
    #   - thanos-sidecar-cloud
    # restart: always
    networks:
      health-monitor:
        ipv4_address: "172.10.0.4"

  thanos-compactor:
    image: quay.io/thanos/thanos:v0.31.0
    volumes:
      - ./thanos/:/etc/thanos/      
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    command:
      - 'compact'
      - '--log.level=debug'
      - '--data-dir=/data'
      - '--objstore.config-file=/etc/thanos/bucket-config.yaml'
      - '--wait'
      # - '--retention.resolution-raw=180d'
      # - '--retention.resolution-5m=180d'
      # - '--retention.resolution-1h=180d'
    # restart: always
    networks:
      health-monitor:
        ipv4_address: "172.10.0.5"

  thanos-ruler:
    image: quay.io/thanos/thanos:v0.31.0
    volumes:
      - ./thanos/:/etc/thanos/      
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    command:
      - 'rule'
      - '--grpc-address=0.0.0.0:10091'
      - '--http-address=0.0.0.0:10902'
      - '--log.level=debug'
      - '--data-dir=/data'
      - '--eval-interval=15s'
      - '--rule-file=/etc/thanos/*.rules.yaml'
      - '--alertmanagers.url=http://alertmanager:9093'
      - '--query=172.10.0.4:10902'
      - '--objstore.config-file=/etc/thanos/bucket-config.yaml'
      - "--label=ruler_cluster=\"cloud\""
      - "--label=ruler_replica=\"0\""
    ports:
      - 10903:10902
    depends_on:
      - thanos-querier
    # restart: always
    networks:
      health-monitor:
        ipv4_address: "172.10.0.6"
